name: Publish r-dsci-grading on DockerHub
on: 
  push: 
    paths: 
      - 'dockerfiles/r-stat-201-grading/Dockerfile'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: oprypin/find-latest-tag@v1
      with:
        repository: UBC-STAT/stat-201-student  # The repository to scan.
        releases-only: true  # We know that all relevant tags have a GitHub release for them.
      id: release
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ubcstat/r-stat-201-grading
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: dockerfiles/r-stat-201-grading
        tags: "${{ steps.release.outputs.tag }}"
